"""Read-only, multi-vendor network inspection tools."""

from .devices_doc import render_devices_doc
from .fixtures import (
    capture_device,
    command_slug,
    fixture_sender,
    load_fixture_evidence,
    scrub_output,
)
from .health import (
    ALL_RULES,
    BASELINE_RULES,
    META_RULES,
    ROLE_INVARIANT_RULES,
    SEVERITY_ORDER,
    evaluate_device,
    evaluate_fabric,
    exit_code_for_severity,
    severity_rank,
)
from .inventory import (
    InventoryError,
    get_default_device_name,
    get_device,
    load_inventory,
)
from .inventory_model import (
    CredentialGroup,
    Defaults,
    Device,
    Expected,
    InventoryFile,
    load_inventory_file,
    parse_inventory,
    reset_inventory_cache,
    resolve_inventory_path,
)
from .lab import DEVICES, PLATFORMS, all_devices, platform_for
from .llm_analysis import (
    LLMAnalysisError,
    analyze_evidence,
    build_analysis_prompt,
    get_provider,
)
from .network_tools import (
    CHECK_TOOLS,
    GOLDEN_SNAPSHOT_FILENAME,
    STATUS_ERROR,
    STATUS_SUCCESS,
    STATUS_UNSUPPORTED,
    check_bgp_neighbors,
    check_fabric,
    check_interfaces,
    check_isis_neighbors,
    check_lldp_neighbors,
    check_sr_policies,
    collect_evidence,
    detect_flaps,
    diff_evidence,
    evidence_intents,
    get_device_facts,
    list_devices,
    load_golden_snapshot,
    load_latest_snapshot,
    run_intent,
    save_golden_snapshot,
    save_snapshot,
)
from .normalize import mask_volatile, normalize_output, strip_preamble
from .parsers import (
    PARSE_FAILED,
    PARSE_OK,
    PARSE_UNAVAILABLE,
    ParseError,
    has_parser,
    parse_intent,
    record_key,
    volatile_fields,
)
from .platforms import (
    ALL_APPROVED_COMMANDS,
    APPROVED_COMMANDS,
    DEFAULT_PLATFORM,
    PLATFORM_INTENTS,
    UnknownPlatformError,
    UnsupportedIntentError,
    all_intents,
    commands_for,
    intents_for,
    is_approved,
    known_platforms,
    supports,
)
from .topology import (
    build_anomaly_report,
    derive_expected,
    find_lldp_disagreements,
    find_neighbors_not_in_inventory,
    find_zero_adjacency_devices,
    format_anomaly_report,
    update_expected_in_yaml,
)

__all__ = [
    # inventory
    "InventoryError",
    "load_inventory",
    "get_device",
    "get_default_device_name",
    "DEVICES",
    "PLATFORMS",
    "all_devices",
    "platform_for",
    # inventory schema and YAML loading (inventory_model.py)
    "InventoryFile",
    "Device",
    "Defaults",
    "CredentialGroup",
    "Expected",
    "parse_inventory",
    "load_inventory_file",
    "resolve_inventory_path",
    "reset_inventory_cache",
    # topology: derived expected counts and the fabric anomaly report
    "derive_expected",
    "build_anomaly_report",
    "format_anomaly_report",
    "find_lldp_disagreements",
    "find_neighbors_not_in_inventory",
    "find_zero_adjacency_devices",
    "update_expected_in_yaml",
    # docs generation
    "render_devices_doc",
    # platforms: the allowlist, keyed by vendor
    "PLATFORM_INTENTS",
    "APPROVED_COMMANDS",
    "ALL_APPROVED_COMMANDS",
    "DEFAULT_PLATFORM",
    "UnknownPlatformError",
    "UnsupportedIntentError",
    "known_platforms",
    "all_intents",
    "intents_for",
    "commands_for",
    "supports",
    "is_approved",
    # network tools
    "CHECK_TOOLS",
    "STATUS_SUCCESS",
    "STATUS_ERROR",
    "STATUS_UNSUPPORTED",
    "list_devices",
    "run_intent",
    "get_device_facts",
    "check_interfaces",
    "check_bgp_neighbors",
    "check_lldp_neighbors",
    "check_isis_neighbors",
    "check_sr_policies",
    "check_fabric",
    "collect_evidence",
    "evidence_intents",
    "save_snapshot",
    "load_latest_snapshot",
    "diff_evidence",
    # golden (pinned) snapshots and flap detection
    "GOLDEN_SNAPSHOT_FILENAME",
    "save_golden_snapshot",
    "load_golden_snapshot",
    "detect_flaps",
    # health: deterministic verdicts over collected evidence (Phase 4)
    "SEVERITY_ORDER",
    "ROLE_INVARIANT_RULES",
    "BASELINE_RULES",
    "META_RULES",
    "ALL_RULES",
    "severity_rank",
    "exit_code_for_severity",
    "evaluate_device",
    "evaluate_fabric",
    # parsing: structured records from raw command output
    "parse_intent",
    "has_parser",
    "record_key",
    "volatile_fields",
    "ParseError",
    "PARSE_OK",
    "PARSE_UNAVAILABLE",
    "PARSE_FAILED",
    # normalization: the diff fallback when no parser exists
    "normalize_output",
    "strip_preamble",
    "mask_volatile",
    # fixtures
    "command_slug",
    "scrub_output",
    "capture_device",
    "fixture_sender",
    "load_fixture_evidence",
    # analysis
    "LLMAnalysisError",
    "get_provider",
    "build_analysis_prompt",
    "analyze_evidence",
]
