"""Shape a log window before a model ever sees it.

Pure functions over already-parsed `logging` records. No I/O, no device access,
no model.

Why this is code and not prompt instructions
---------------------------------------------
A raw `show logging last 200` window on this fabric is **68% the collector's
own SSH sessions**, and most of the remainder is `exec` session registration
noise from the same source. Measured on PE2's `broken` capture: 200 entries in,
**20** genuine network events out.

Leaving that reduction to the model was the alternative, and it is worse on
three counts, in increasing order of importance:

1. **Context budget.** 37,962 characters of window, of which ~34,000 are noise
   the model must read and discard on every single call.
2. **Testability.** "The model usually ignores SSH churn" is not a property
   anything can assert. `drop_collector_noise` is.
3. **Determinism.** The same window must produce the same filtered set every
   time, or two runs of one investigation can correlate against different
   evidence and reach different conclusions. That is the reproducibility the
   whole deterministic-descent argument rests on, and handing it to a
   probabilistic step at the last moment would give it away for nothing.

The corollary matters too: because filtering is code, **what was dropped is
knowable**. :func:`shape_window` reports the counts, so a report can say "20 of
200 entries were network events" rather than silently presenting 20 and
implying that was all there was.

A measured correction to OBS-014
---------------------------------
OBS-014 found one event stored **1,346 times** and concluded any count over
that corpus is fiction without deduplication. That is true of **Loki**, and it
is *not* true of the device's own buffer: deduplicating PE2's 200-entry window
removes exactly **zero** records. The duplication is introduced by the syslog
pipeline, not present at the source.

:func:`dedupe` is kept anyway, because B-206 will read the same records back
out of Loki where the duplication is real. It is a no-op on this source and
load-bearing on the next one, which is worth stating so nobody deletes it as
dead code.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

__all__ = [
    "COLLECTOR_FACILITIES",
    "ShapedWindow",
    "dedupe",
    "drop_collector_noise",
    "filter_to_subject",
    "shape_window",
]

#: Facilities generated by this tool's own presence rather than by the network.
#:
#: `SECURITY-SSHD_SYSLOG_PRX` is netmiko sessions opening and closing --
#: measured at 1,187 of 1,219 lines fabric-wide (OBS-014), and 137 of 200 in a
#: single device window. `SYSDB-SYSDB` is `exec` session registration churn
#: from the same sessions.
#:
#: Both are *observations of the observer*. Dropping them is not hiding
#: evidence: no investigation of a BGP session has ever been advanced by
#: knowing that the collector logged in again.
COLLECTOR_FACILITIES: frozenset[str] = frozenset(
    {"SECURITY-SSHD_SYSLOG_PRX", "SYSDB-SYSDB"}
)


@dataclass(frozen=True)
class ShapedWindow:
    """A filtered window, and an honest account of what was removed."""

    records: tuple[dict[str, Any], ...] = field(default_factory=tuple)
    total_in: int = 0
    duplicates_removed: int = 0
    collector_noise_removed: int = 0
    unrelated_removed: int = 0

    @property
    def is_empty(self) -> bool:
        return not self.records

    def summary(self) -> str:
        """One line a report can cite about the window itself."""

        return (
            f"{len(self.records)} of {self.total_in} log entries retained "
            f"({self.collector_noise_removed} collector-generated, "
            f"{self.duplicates_removed} duplicate, "
            f"{self.unrelated_removed} unrelated to the subject)"
        )


def dedupe(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Drop records identical in device timestamp, mnemonic and text.

    Keyed on the **device's own** timestamp, never an ingest timestamp: the
    same event re-delivered carries the same device clock reading and a
    different arrival time, so keying on arrival would preserve every copy.
    """

    seen: set[tuple[str, str, str]] = set()
    kept: list[dict[str, Any]] = []
    for record in records:
        key = (record.get("timestamp", ""), record.get("mnemonic", ""), record.get("text", ""))
        if key in seen:
            continue
        seen.add(key)
        kept.append(record)
    return kept


def drop_collector_noise(
    records: list[dict[str, Any]], *, facilities: frozenset[str] = COLLECTOR_FACILITIES
) -> list[dict[str, Any]]:
    """Remove entries this tool's own polling generated."""

    return [r for r in records if r.get("facility") not in facilities]


def filter_to_subject(records: list[dict[str, Any]], subject: str | None) -> list[dict[str, Any]]:
    """Keep entries that mention the subject, when a subject is given.

    Deliberately a plain substring match over the message text, and
    deliberately **not** applied by default. An interface shutdown that
    isolates a peer never names the peer's address, so filtering a
    `bgp_session` window to the peer address would discard the very events that
    explain it -- as measured on the `broken` label, where the causal events
    name `GigabitEthernet0/0/0/0` and `P1`, not `10.255.0.12`.
    """

    if not subject:
        return list(records)
    return [r for r in records if subject in r.get("text", "")]


def shape_window(
    records: list[dict[str, Any]],
    *,
    subject: str | None = None,
    drop_noise: bool = True,
) -> ShapedWindow:
    """Dedupe, drop collector noise, optionally narrow to the subject.

    Order matters: dedupe first so a duplicated noise line is counted once as
    noise rather than many times, and narrow to the subject last so the
    "unrelated" count means what it says.
    """

    total = len(records)

    deduped = dedupe(records)
    duplicates = total - len(deduped)

    kept = drop_collector_noise(deduped) if drop_noise else deduped
    noise = len(deduped) - len(kept)

    narrowed = filter_to_subject(kept, subject)
    unrelated = len(kept) - len(narrowed)

    return ShapedWindow(
        records=tuple(narrowed),
        total_in=total,
        duplicates_removed=duplicates,
        collector_noise_removed=noise,
        unrelated_removed=unrelated,
    )
